name: Install Kyverno into created cluster

on:
  # push:
  #   branches:
  #     - main
  workflow_dispatch:

jobs:
  install_kyverno:
    runs-on: ubuntu-latest
    name: Install latest (main branch) Kyverno to cluster
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DO_API_KEY }}

      - name: Save DigitalOcean kubeconfig with short-lived credentials
        id: gen-kube-config
        run: mkdir -p ~/.kube && echo $(doctl kubernetes cluster kubeconfig show --expiry-seconds 600 do-challenge-cluster) > ~/.kube/config 2>&1

      - name: Download Kubectl and Helm
        run: |
          curl -LO "https://dl.k8s.io/release/v1.21.0/bin/linux/amd64/kubectl" -o kubectl
          chmod +x kubectl
          mv kubectl /usr/local/bin

      - name: Install Kyverno via Kubectl
        run: kubectl apply -f https://raw.githubusercontent.com/kyverno/kyverno/main/config/release/install.yaml
