name: Create terraform plan for Kubernetes cluster

on: 
  pull_request:

  workflow_dispatch:

jobs:
  plan:
    runs-on: ubuntu-latest
    name: Create a plan for a Digital Ocean Kubernets cluster
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Run Terraform plan
        uses: dflook/terraform-plan@v1
        with:
          path: Terraform
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.DO_SPACES_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.DO_SPACES_AWS_SECRET_ACCESS_KEY }}
          TF_VAR_do_token: ${{ secrets.DO_API_KEY }}
